# Assignment4

# Task1

In [4]:
# working of try()  
def divide(x, y): 
    try: 
        # Floor Division : Gives only Fractional Part as Answer 
        result = x // y 
        print("Yeah ! Your answer is :", result) 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
  
#Look at parameters and note the working of Program 
divide(5, 0) 

Sorry ! You are dividing by zero 


In [3]:
def divide():
    return 5/0

try:
    divide()
except ZeroDivisionError as ze:
    print("you are dividing a number by ZERO!!")
except:
    print("Any other exception")


you are dividing a number by ZERO!!


In [8]:
def throws():
    return 5/0

try:
    throws()
except ZeroDivisionError:
    print("division by zero!")
except Exception:
    print('Caught an exception')
finally:
    print('In finally block for cleanup')

division by zero!
In finally block for cleanup


In [9]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

# Use list comprehension instead of looping over each of the predicates
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)


Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


# Task 2:

In [24]:
import numpy as np
x = np.array([1, 2, 3, 5])


In [25]:
N = 3
np.vander(x, N)



array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [26]:
np.column_stack([x**(N-1-i) for i in range(N)])



array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [29]:
x = np.array([1, 2, 3, 5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [30]:

np.vander(x, increasing=True)


array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [31]:
np.linalg.det(np.vander(x))

48.00000000000003

In [22]:
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48

In [33]:
os.getcwd()

NameError: name 'os' is not defined

In [34]:
import os
os.getcwd()

'C:\\Users\\ysjam'